#!/bin/bash

clear

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         hacka.re Terminal UI v2.0 - Demo                  ║"
echo "║                   REIMPLEMENTED FROM SCRATCH              ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "This is a complete reimplementation of the hacka.re terminal GUI"
echo "with a clean architecture and improved features."
echo ""
echo "✨ MAIN FEATURES:"
echo ""
echo "📋 FILTERABLE MENU:"
echo "   • Type to search/filter menu items in real-time"
echo "   • Press numbers 0-9 for quick selection"
echo "   • Use ↑/↓ arrow keys to navigate"
echo "   • ESC clears filter, ESC again exits"
echo "   • Enter selects the highlighted item"
echo ""
echo "📊 INFO PANEL:"
echo "   • Detailed information panel on the right"
echo "   • Properly handles line breaks and formatting"
echo "   • Shows bullet points and lists correctly"
echo "   • Automatic text wrapping"
echo ""
echo "⚙️  SETTINGS MODAL:"
echo "   • Full settings configuration interface"
echo "   • Multiple field types:"
echo "     - Text fields (API Key, Base URL)"
echo "     - Dropdowns (Provider, Model, Theme)"
echo "     - Numbers (Max Tokens)"
echo "     - Floats (Temperature)"
echo "     - Toggles (Stream Mode, YOLO Mode)"
echo "   • Field validation"
echo "   • Dynamic model list based on provider"
echo "   • Press Enter to edit, S to save"
echo ""
echo "🏗️  CLEAN ARCHITECTURE:"
echo "   • No event dropping issues"
echo "   • Proper event loop handling"
echo "   • Modular component design"
echo "   • State-based rendering"
echo ""
echo "Press Enter to launch the Rich TUI Mode..."
read

# Launch the rich TUI
./hackare-tui -mode rich