# Example configuration for hacka.re verifier

# Basic settings
project_path: /path/to/hacka.re
output_dir: reports
report_format: html
log_level: info
timeout: 30

# Module configurations
modules:
  # Static code analysis
  static_analysis:
    enabled: true
    files_to_analyze:
      - "*.js"
      - "*.html"
      - "*.css"
    exclude_dirs:
      - node_modules
      - dist
      - build
      - _venv
    patterns:
      tracking_code:
        - "google-analytics"
        - "googletagmanager"
        - "gtag"
        - "analytics\\.js"
        - "mixpanel"
        - "segment"
        - "amplitude"
        - "tracking"
      external_requests:
        - "fetch\\(['\"]https?://"
        - "\\.ajax\\(\\s*{\\s*url\\s*:\\s*['\"]https?://"
        - "\\.get\\(['\"]https?://"
        - "\\.post\\(['\"]https?://"
        - "new XMLHttpRequest\\(\\s*\\)\\s*\\.open\\(['\"]GET['\"],\\s*['\"]https?://"
        - "new XMLHttpRequest\\(\\s*\\)\\s*\\.open\\(['\"]POST['\"],\\s*['\"]https?://"
        - "axios\\.get\\(['\"]https?://"
        - "axios\\.post\\(['\"]https?://"
      api_key_storage:
        - "localStorage\\.setItem\\(['\"]api[_-]?key['\"]"
        - "localStorage\\.getItem\\(['\"]api[_-]?key['\"]"
        - "localStorage\\[['\"]api[_-]?key['\"]\\]"
      encryption_usage:
        - "encrypt"
        - "decrypt"
        - "hash"
        - "sign"
        - "verify"
        - "nacl"
        - "tweetnacl"
        - "crypto"

  # Network traffic analysis
  network_analysis:
    enabled: true
    allowed_domains:
      - api.groq.com
      - api.openai.com
      - localhost
      - 127.0.0.1
    blocked_domains:
      - google-analytics.com
      - googletagmanager.com
      - doubleclick.net
      - facebook.net
      - facebook.com
      - twitter.com
      - linkedin.com
      - amplitude.com
      - mixpanel.com
      - segment.io
      - hotjar.com
    test_scenarios:
      - page_load
      - api_key_entry
      - chat_message
      - settings_change
      - function_calling
    browser: chromium
    headless: true

  # Cryptographic implementation audit
  crypto_audit:
    enabled: true
    files_to_analyze:
      - js/utils/crypto-utils.js
      - js/utils/rc4-utils.js
      - js/services/encryption-service.js
      - js/services/storage-service.js
      - js/services/link-sharing-service.js
      - js/services/share-service.js
    test_vectors:
      rc4:
        key: Key
        plaintext: Plaintext
        ciphertext: BBF316E8D940AF0AD3
    crypto_requirements:
      min_key_size: 256
      min_iterations: 1000

  # Browser storage analysis
  storage_analysis:
    enabled: true
    storage_keys:
      - api_key
      - apiKey
      - history
      - conversation
      - messages
      - settings
      - model
      - namespace
    test_scenarios:
      - api_key_storage
      - conversation_history
      - settings_persistence
      - namespace_isolation
    browser: chromium
    headless: true

  # Dependency verification
  dependency_verification:
    enabled: true
    required_local_libs:
      - dompurify
      - marked
      - tweetnacl
      - qrcode
    check_external_requests: true
    check_integrity: true
    check_vulnerabilities: true

  # Report generation
  report_generation:
    enabled: true
    formats:
      - html
      - json
      - markdown
    include_screenshots: true
    include_code_snippets: true
    include_recommendations: true
    include_summary: true
    include_details: true
