# Custom configuration for hacka.re verifier
modules:
  static_analysis:
    patterns:
      tracking_code:
        - 'google-analytics'
        - 'googletagmanager'
        - 'gtag'
        - 'analytics\.js'
        - 'mixpanel'
        - 'segment'
        - 'amplitude'
        # Remove the generic 'tracking' pattern that causes false positives
    exclude_dirs:
      - 'node_modules'
      - 'dist'
      - 'build'
      - '_venv'
      - 'reports'
      - 'hacka_re_verifier'
  network_analysis:
    allowed_domains:
      - 'api.groq.com'
      - 'api.openai.com'
      - 'localhost'
      - '127.0.0.1'
      - 'worldtimeapi.org'  # Allow this domain for the time API
  report_generation:
    output_dir: '/Users/user/dev/hacka.re/custom_reports'
    formats: ['html']
